# Generated by Django 5.2.6 on 2026-09-28 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='Technical', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'content_topics',
            },
        ),
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tone', models.CharField(choices=[('PROFESSIONAL', 'Professional'), ('CASUAL', 'Casual'), ('THOUGHT_LEADERSHIP', 'Thought Leadership'), ('STORYTELLING', 'Storytelling'), ('EDUCATIONAL', 'Educational')], default='PROFESSIONAL', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=32)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=True)),
                ('human_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'linkedin_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('reactions', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('profile_views_generated', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='content.linkedinpost')),
            ],
            options={
                'db_table': 'post_performances',
            },
        ),
    ]
