# Generated by Django 5.2.6 on 2026-09-28 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('html_url', models.URLField()),
                ('primary_language', models.CharField(blank=True, max_length=100)),
                ('languages', models.JSONField(blank=True, default=dict)),
                ('stars_count', models.PositiveIntegerField(default=0)),
                ('forks_count', models.PositiveIntegerField(default=0)),
                ('is_fork', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repositories', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'github_repositories',
                'unique_together': {('tenant', 'full_name')},
            },
        ),
        migrations.CreateModel(
            name='GitHubInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_text', models.TextField()),
                ('suggested_post_topic', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_insights', to='tenants.tenant')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='github.githubrepository')),
            ],
            options={
                'db_table': 'github_insights',
            },
        ),
        migrations.CreateModel(
            name='GitHubActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('COMMIT', 'Commit'), ('RELEASE', 'Release'), ('PULL_REQUEST', 'Pull Request'), ('ISSUE', 'Issue')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('technologies_detected', models.JSONField(blank=True, default=list)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='github.githubrepository')),
            ],
            options={
                'db_table': 'github_activities',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
