# Generated by Django 5.2.6 on 2026-09-28 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('SKILL_GAP', 'Skill Gap'), ('MARKET_TREND', 'Market Trend'), ('PROFILE_STRENGTH', 'Profile Strength'), ('CONTENT_SUGGESTION', 'Content Suggestion')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('actionable_step', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_insights', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_career_insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
